scara_joint_velocity_controller/joint_velocity:
    type: std_msgs/Float64MultiArray
    joint1: 
        min: -1.0        
        max: 1.0
        to: data[0]
        default: 0.0
    joint2: 
        min: -1.0
        max: 1.0
        to: data[1]
        default: 0.0      
    joint3: 
        min: -1.0
        max: 1.0
        to: data[2]
        default: 0.0